CREATE TABLE links(
    id SERIAL PRIMARY KEY,
    title VARCHAR(100),
    url VARCHAR(100),
    client VARCHAR(50),
    added_at TIMESTAMP WITH TIME ZONE,
    archive BOOLEAN DEFAULT FALSE,
    inserted_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);