name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: links_repo_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.16.3 # Define the elixir version [required]
        otp-version: 26.0 # Define the OTP version [required]
        experimental-otp: true # Flag needed for OpenSSL stuff
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      env:
        SECRET_KEY_BASE: "SALTy salt"
        POSTGRES_HOST: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_PORT: 5432
        MIX_ENV: test
      run: |
        mix ecto.create
        mix ecto.migrate
        mix test
